name: "releaser"
on:
  push:
    tags:
      - "*"
jobs:
  golangci:
    name: "Lint code"
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/setup-go@v3
        with: 
          go-version: 1.18
      - uses: actions/checkout@v3
      - 
        name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  releaser:
    name: "Release builds"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with: 
          go-version: 1.18
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
